# Generated by Django 4.1.4 on 2022-12-27 17:19

import app_core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_core', '0005_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to=app_core.models.recipe_image_file_patch),
        ),
    ]
